version: '2.4'
services:
  core:
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: cr.loongnix.cn/library/mysql:5.7.34
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8
    environment:
      DB_PORT: $DB_PORT
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
    networks:
      - net
